# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
variables:
  makeFilePath: ./Makefile

trigger:
  batch: true
  branches:
    include:
    - master
    - feature/*
    - patch/*

resources:
- repo: self

jobs:  
- job: deliveryjobci
  displayName: "Delivery CI"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    fullCI: $[ startsWith(variables['build.sourceBranch'], 'refs/heads/release/pplavetzki-apis') ]
    buildImage: $[ eq(variables['build.sourceBranch'], 'refs/heads/master') ]
  steps:
  - task: Bash@3
    displayName: "Build the TestRunner"
    env:
      AZURE: $(AZURE)
      SUBSCRIPTION: $(SUBSCRIPTION)
      ACR_PASSWORD: $(ACR_PASSWORD)
    inputs:
      targetType: inline
      script: make validation
  - task: Bash@3
    condition: or(eq(variables['buildImage'],True),eq(variables['fullCI'],True))
    displayName: "Publish Image"
    env:
      AZURE: $(AZURE)
      SUBSCRIPTION: $(SUBSCRIPTION)
      ACR_PASSWORD: $(ACR_PASSWORD)
    inputs:
      targetType: inline
      script: make publish